### ISSUE TITLE
Can't compile any of the samples

### ISSUE THREAD

**Issue by Skaruts** [zetashift/godotnim-samples#2]
When I did `nake build` I got an error and a warning right at the beginning, but this I managed to work around. The warning was:
```
# many Hint lines before this
Hint: ospaths [Processing]
C:\Godot\Godot-Nim\nimway\nakefile.nim(4, 12) Warning: import os.nim instead; ospaths is deprecated [Deprecated]
```
I suppose the code is a little outdated. For some reason the warning seems to not show up (or maybe I missed it) when I fix the error below. 
```
# many Hint lines before this
Hint: rodutils [Processing]
C:\Godot\Godot-Nim\nimway\nakefile.nim(9, 15) Error: usage of 'isNil' is a user-defined error
```
I fixed this by deleting the first condition at line 9
```nim
# I turned this
if godotBin.isNil or godotBin.len == 0:

# into this
if godotBin.len == 0:     
```
(Though I would assume `isNil` should work. I use it in my own stuff.)

However, then I still couldn't compile either of the samples. They both give me errors at the point when Nim compiler is compiling everything. 

Compiling on Nimway gives me this error:

```
# many Hint lines before this
Hint: control [Processing]
Hint: canvas_item [Processing]
C:\Godot\Godot-Nim\nimway\src\cell.nim(9, 7) template/generic instantiation of `gdobj` from here
C:\Godot\Godot-Nim\nimway\src\cell.nim(15, 5) Error: undeclared identifier: 'anim'
       Tip: 4 messages have been suppressed, use --verbose to show them.
     Error: Execution failed with exit code 1
        ... Command: "C:\nim-1.0.4\bin\nim.exe" c --noNimblePath -d:NimblePkgVersion=0.1.0 --path:"C:\Users\Skaruts\.nimble\pkgs\godot-0.7.26" --path:"C:\Users\Skaruts\.nimble\pkgs\compiler-1.0.4" "-o:..\_dlls\nim_64.dll"  "..\src\stub"
```

And compiling on DodgeTheNim gives me this one:

```
# many Hint lines before this
Hint: rigid_body_2d [Processing]
Hint: physics_body_2d [Processing]
C:\Godot\Godot-Nim\dodgethenim\src\player.nim(4, 7) template/generic instantiation of `gdobj` from here
C:\Godot\Godot-Nim\dodgethenim\src\player.nim(14, 9) Error: type mismatch: got <>
but expected one of:
proc hide(self: CanvasItem)

expression: hide()
       Tip: 5 messages have been suppressed, use --verbose to show them.
     Error: Execution failed with exit code 1
        ... Command: "C:\nim-1.0.4\bin\nim.exe" c --noNimblePath -d:NimblePkgVersion=0.1.0 --path:"C:\Users\Skaruts\.nimble\pkgs\godot-0.7.26" --path:"C:\Users\Skaruts\.nimble\pkgs\compiler-1.0.4" "-o:..\_dlls\nim_64.dll"  "..\src\stub"
```

I don't really know how the nakefile works, so I can't really tell what can be causing this. I tried replacing your nakefile.nim with godot-nim-stub's nakefile.nim, and it didn't work either, although I got different errors, but also at Nim's compile time.

_EDIT: on afterthought, it seems the error is the same on both cases (`template/generic instantiation of 'gdobj'`). Maybe it's not being able to `import godot`. When I used godot-nim-stub's nakefile.nim with Nimway, the error was on `cell.nim`'s line 2: `can't load file animation_player`. So maybe that's the case here, but with file `godot` and the compiler is only reporting the errors derived from that. I could be totally wrong, it's just what came to my mind._

I also manually cleaned the generated folders between attempts at compiling, because that was making nake generate them in the wrong places (maybe it can't overwrite existing files).

My nim version is 1.0.4, and godot is 3.2_rc1.

**Comment by zetashift** [comment]
Yeah these samples are really old, compared to the progress that's been made with Nim(after 0.20) and godot-nim (some rewrites to maintain 0.18 and  1.0 compatibility).

I could refactor this to make it work on the latest version. But I don't really think it's worth the effort. 
I think this because, Nim <-> GDScript is still quite straightforward. The stub should show you how to do most things.
Also most refactoring will be adding `self` to alot of lines because of: https://github.com/pragmagic/godot-nim/pull/45 
The rest should be the same(e.g. registering signals in Nim). 
I knew this was outdated and I should've probably updated the README to reflect that. I'm making a new sample based off: https://www.gdquest.com/product/godot/make-pro-2d-games/ but exams are 'till next thursday.

Personally I would just work out of godot-nim-stub and if you have any questions hit me up on the Nim discord/gitter or on Godot's gdnative discord channel, you can ping me @zetashift 
EDIT: You can ignore the nake errors that's because it's made for Nim 0.18 and it messing with it will just give you unnecessary headache. If the latest godot-nim-stub compiles you are all set and ready to write Nim.

**Comment by Skaruts** [comment]
Yea, I was watching some GDNative tutorials by ProggerParrot before I went to sleep, and they helped me understand the whole dll setup in godot better, so I could probably work from the stub. Although I've looked at it with a fresh mind now, and with your suggestions in mind I've been tinkering with Nimway and I got it to work. :) (Using the stub's nakefile.nim.)

Btw, while running it I also noticed the cells weren't reacting as they ought to, and I found the issue. There are two lines switched in the step code:

```nim
if livingNeighbors < 2 or livingNeighbors > 3:
  kinds.add(CellKind.Living)  # this should kill the cell 
elif livingNeighbors == 2 or livingNeighbors == 3:
  kinds.add(CellKind.Dead)    # this should revive the cell
```

If you want the working code just let me know. I did some other personal-preference-adjustments to the code, though. I haven't yet touched the other sample.

**Comment by zetashift** [comment]
Yes feel free to make a PR and I'l accept it ASAP and change the readme.

**Comment by zetashift** [comment]
Closing this, even though it DodgeTheNim sortof works, Nimway doesn't work, main objective of this repo was also to show how godot-nim does certain things.
And with the oldgensym toggle we still need to wait for a solution from godot-nim
